ros2/rosidl_python

- python_cmake_module/package.xml
- rosidl_generator_py/package.xml
This commit will be fast-forwarded onto master if approved.
> Prepare 0.5.0

- rosidl_generator_py/CMakeLists.txt
- rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
> Fix rosidl target name assumptions

- rosidl_generator_py/resource/_msg_support.c.em
> rename dynamic array to sequence

- rosidl_generator_py/resource/_msg.py.em
See https://docs.python.org/3/library/collections.html
> replace deprecated collections usage with collections.abc

- rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
This is for compatibility with uncrustify v0.68.
Connects to ros2/rosidl#340
Connects to ament/uncrustify_vendor#3
> Change uncrustify max line length to 0

- rosidl_generator_py/msg/Constants.msg
- rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
- rosidl_generator_py/test/test_interfaces.py
As reported in https://github.com/ros2/rosidl_python/pull/45#discussion_r277385940
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6766)](https://ci.ros2.org/job/ci_linux/6766/)
> fix boolean constant in Python mapping

- rosidl_runtime_py/test/rosidl_runtime_py/test_convert.py
Connects to https://github.com/ros2/rcl_interfaces/issues/58
> [rosidl_runtime_py] Use new test interface definitions

- rosidl_generator_py/CMakeLists.txt
- rosidl_generator_py/msg/WStrings.msg
- rosidl_generator_py/resource/_msg.py.em
- rosidl_generator_py/resource/_msg_support.c.em
- rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
- rosidl_generator_py/test/test_interfaces.py
Connect to ros2/rosidl#352.
While waiting for ros2/rcl_interfaces#58 the patch (without tests) can already be reviewed.
> add WString support

- rosidl_runtime_py/package.xml
- rosidl_runtime_py/test/test_xmllint.py
Noticed this as my editors' linter was reporting the failure but all the tests were passing
> add xmllint linter test

- rosidl_generator_py/resource/_msg_support.c.em
Since we currently don't have a way to construct a Python message class without its default values we have to remove them before populating the `array.array` fields using `frombytes`.
Related to ros2/test_interface_files#5.
> fix conversion from C to Python in case a sequence has default values

- rosidl_runtime_py/rosidl_runtime_py/convert.py
Precisely what the title says.
Connected to https://github.com/ros2/ros2cli/pull/304.
> Fix type name queries for string types.

- rosidl_runtime_py/rosidl_runtime_py/set_message.py
- rosidl_runtime_py/test/rosidl_runtime_py/test_set_message.py
> [dashing backport] handle set_message_fields given some non-basic type (#68)

- rosidl_runtime_py/rosidl_runtime_py/set_message.py
> [backport dashing] fix set_message_fields for numpy array

- rosidl_runtime_py/setup.py
> install package manifest

- rosidl_runtime_py/setup.py
Backport #86 and https://github.com/ros2/rosidl_runtime_py/pull/2
> [dashing backport] Backport changes to rosidl_runtime_py/setup.py

- rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
Backport #75.
@jpsamper2009 FYI
> [dashing backport] Find numpy headers in non-debian paths

- rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
CI builds in ament/ament_package#112.
> use f-string

- rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em
- rosidl_generator_py/resource/_msg_support.c.em
> update includes to use non-entry point headers from detail subdir

- rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
- rosidl_generator_py/resource/_msg_support.c.em
> ensure the Python support target links against the C generator target

- rosidl_generator_py/pytest.ini
- rosidl_generator_py/resource/_msg_support.c.em
Fast-forwarding foxy branch.
This should help resolve one of the outstanding failures in ros2/ci#503
> Fast-forward Foxy

- rosidl_generator_py/resource/_msg_support.c.em
> [eloquent] fix too early decref of WString when converting from Python to C (#117)

- rosidl_generator_py/resource/_msg_support.c.em
> [dashing] fix too early decref of WString when converting from Python to C (#117)

- rosidl_generator_py/package.xml
> Remove trailing whitespace.

- rosidl_generator_py/package.xml
Precisely what the title says.
> Update package maintainers

- rosidl_generator_py/package.xml
> Adding maintainer

- rosidl_generator_py/resource/_msg_support.c.em
address https://github.com/ros2/rclpy/issues/881
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
> Change decode mode into replace.

- rosidl_generator_py/CMakeLists.txt
- rosidl_generator_py/package.xml
- rosidl_generator_py/resource/_action.py.em
- rosidl_generator_py/resource/_action_pkg_typesupport_entry_point.c.em
- rosidl_generator_py/resource/_idl_pkg_typesupport_entry_point.c.em
- rosidl_generator_py/resource/_msg.py.em
- rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em
- rosidl_generator_py/resource/_msg_support.c.em
- rosidl_generator_py/resource/_srv.py.em
- rosidl_generator_py/resource/_srv_pkg_typesupport_entry_point.c.em
- rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
Depends on https://github.com/ros2/rosidl/pull/696
> Replace rosidl_cmake imports with rosidl_pycommon

- rosidl_generator_py/CHANGELOG.rst
- rosidl_generator_py/package.xml
Changelog update and version bump. I will follow up with the tag and bloom once this is merged.
NOTE: We might wanna rebase to keep the commits as per the history in this repo.
> Rolling release.
