rosidl_generator_py/resource/_msg.py.em
connects to ros2/ci#203
as discussed in https://github.com/ros2/build_cop/issues/104
=> Prevent flake8-builtins A003

rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_msg_support.c.em
This separates memory allocation out from convert_from_py function. Now it uses separate create_message function to allocate message, making it explicit gives better control where and how memory is allocated and freed.
See https://github.com/ros2/rosidl_python/issues/5 for details.
=> Fixes memory leaks for nested fields

rosidl_generator_py/cmake/custom_command.cmake, rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake, rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_msg_support.c.em, rosidl_generator_py/resource/_srv.py.em, rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
Closes #13 . 
This PR allows the generation of messages and services that are defined in the module `action`.
It depends on https://github.com/ros2/rosidl/pull/308 , https://github.com/ros2/rosidl_dds/pull/44 and https://github.com/ros2/rosidl_typesupport/pull/33 to compile successfully.
It was tested with the definitions found in [this rcl_interfaces' branch](https://github.com/ros2/rcl_interfaces/tree/sloretz/msg_srv_in_action/test_msgs) .
connects to ros2/rosidl#301
=> Generate msg/srv from within an 'action' directory/module

rosidl_generator_py/cmake/custom_command.cmake, rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
The target dependency won't exist at cmake configure time before the first build if it is generated. Since the custom command is in a subdirectory it cannot depend on the generated files directly. Instead it depends on a target from the parent directory which depends on the IDL files.
connects to ros2/rcl_interfaces#47
=> Allow generated IDL files

rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/test/test_interfaces.py
This adds a `_slot_types` field to python message classes as was requested here: https://github.com/ros2/rosidl_python/issues/16
This attempts to remain as true to the ROS1 functionality as possible
=> Adding a get_slot_fields_and_types method to python msg classes

rosidl_generator_py/resource/_msg_support.c.em
This pull request adds ASCII codification and de-codification steps whenever dealing with string and char message fields. 
Fixes https://github.com/ros2/ros2cli/issues/176 (which is actually one instance of an issue that is Python support wide).
=> Enforce ASCII characters on string and char fields

python_cmake_module/cmake/Modules/FindPythonExtra.cmake, rosidl_generator_py/cmake/custom_command.cmake, rosidl_generator_py/cmake/register_py.cmake, rosidl_generator_py/cmake/rosidl_generator_py_generate_action_interfaces.cmake, rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake, rosidl_generator_py/resource/_action.py.em, rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_srv.py.em, rosidl_generator_py/rosidl_generator_py/generate_py_impl.py, rosidl_generator_py/rosidl_generator_py/import_type_support_impl.py
Closes #14 
This PR:
- Adds the required `rosidl_python/rosidl_generator_py/resource/_action.py.em` template file with the proper imports for the generated action messages/services.
- Adds action typesupport bits to the `_msg_pkg_typesupport_entry_point.c.em` script.
- Adds logic to the `rosidl_generator_py` so that it can handle the new action's template.
=> Python typesupport for Actions

rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
Since actions are added separately from the generation of messages and services within them, it would be difficult to get the import order right. Instead this PR ignores the order
connects to ros2/rosidl#348
CI at ros2/rosidl_typesupport#44
required by ros2/rcl_interfaces#62
This PR should be backported to crystal
=> Ignore import order on generated imports

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/cmake/register_py.cmake, rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake, rosidl_generator_py/resource/_action.py.em, rosidl_generator_py/resource/_idl.py.em, rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_support.c.em, rosidl_generator_py/resource/_srv.py.em, rosidl_generator_py/rosidl_generator_py-extras.cmake.in, rosidl_generator_py/rosidl_generator_py/generate_py_impl.py, rosidl_generator_py/test/test_interfaces.py
Implements the latest version of the design article describing the type mapping for Python (including the latest change ros2/design#217).
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6524)](http://ci.ros2.org/job/ci_linux/6524/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2866)](http://ci.ros2.org/job/ci_linux-aarch64/2866/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5342)](http://ci.ros2.org/job/ci_osx/5342/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6316)](http://ci.ros2.org/job/ci_windows/6316/)
=> map Arrays to numpy.ndarray() and Sequences to array.array()

rosidl_runtime_py/package.xml, rosidl_runtime_py/rosidl_runtime_py/__init__.py, rosidl_runtime_py/rosidl_runtime_py/convert.py, rosidl_runtime_py/rosidl_runtime_py/set_message.py, rosidl_runtime_py/setup.py, rosidl_runtime_py/test/rosidl_runtime_py/test_convert.py, rosidl_runtime_py/test/rosidl_runtime_py/test_set_message.py, rosidl_runtime_py/test/test_copyright.py, rosidl_runtime_py/test/test_flake8.py, rosidl_runtime_py/test/test_pep257.py
Migrated utility functions for working with Python ROS messages from the package `ros2topic`.
The intention is to reuse these functions in other CLI tools: `ros2service` and `ros2action`.
Replaces ros2/rclpy#285.
=> Add rosidl_runtime_py package

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
Follow up of #35.
Fixes ros2/build_cop#176.
Depends on ros2/ci#272.
Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6373)](https://ci.ros2.org/job/ci_windows/6373/) (failing at `test` time)
After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6395)](https://ci.ros2.org/job/ci_windows/6395/)
=> fix numpy usage for Windows debug builds

rosidl_runtime_py/rosidl_runtime_py/convert.py
Fixes ros2/ros2cli#213 which is a regression of #35.
Only Linux build since CI won't say much: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6599)](https://ci.ros2.org/job/ci_linux/6599/)
=> fix echo of numpy.number values

rosidl_generator_py/package.xml
The build is currently failing due to the numpy import in the template
http://build.ros2.orgjob/Dbin_uB64__rosidl_generator_py__ubuntu_bionic_amd64__binary/1/console
```
06:05:10 [ 89%] Generating Python code for ROS interfaces
06:05:10 cd /tmp/binarydeb/ros-dashing-rosidl-generator-py-0.7.0/obj-x86_64-linux-gnu/rosidl_generator_py_custom__py && /usr/bin/python3 /tmp/binarydeb/ros-dashing-rosidl-generator-py-0.7.0/bin/rosidl_generator_py --generator-arguments-file /tmp/binarydeb/ros-dashing-rosidl-generator-py-0.7.0/obj-x86_64-linux-gnu/rosidl_generator_py__arguments.json --typesupport-impls "rosidl_typesupport_c;rosidl_typesupport_fastrtps_c;rosidl_typesupport_opensplice_c"
06:05:10 ModuleNotFoundError in template '/tmp/binarydeb/ros-dashing-rosidl-generator-py-0.7.0/resource/_msg.py.em': …
```
=> Add numpy dependency to package.xml.

rosidl_generator_py/rosidl_generator_py/import_type_support_impl.py
Added in #21 specifically for actions the keyword argument is not used anymore.
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6692)](https://ci.ros2.org/job/ci_linux/6692/)
=> remove obsolete argument mod_prefix

rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
Replaces parts of #42.
Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6735)](https://ci.ros2.org/job/ci_linux/6735/) (8 test failures)
After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6736)](https://ci.ros2.org/job/ci_linux/6736/) (3 test failures)
=> use quotes with least escaping for Python string literals

rosidl_generator_py/test/test_interfaces.py
Note that for generated code, we unconditionally disable the
flake8-quote check Q003 (Change outer quotes to avoid escaping
inner quotes).  For non-string types, this will have no effect.
For string types, it could be fairly expensive to scan strings
for single or double quotes.  The expense just doesn't seem
worth it and the resulting return value won't be exactly what
the user typed into their .msg file.
Connects to https://github.com/ros2/build_cop/issues/179
=> Fix quoted strings for new flake8-quote check.

rosidl_generator_py/resource/_action.py.em, rosidl_generator_py/resource/_action_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_idl_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_msg_support.c.em, rosidl_generator_py/resource/_srv.py.em, rosidl_generator_py/resource/_srv_pkg_typesupport_entry_point.c.em, rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
=> update code to match refactoring of rosidl definitions

rosidl_generator_py/resource/_action.py.em, rosidl_generator_py/resource/_action_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_msg_support.c.em, rosidl_generator_py/resource/_srv.py.em, rosidl_generator_py/resource/_srv_pkg_typesupport_entry_point.c.em, rosidl_generator_py/rosidl_generator_py/generate_py_impl.py, rosidl_runtime_py/rosidl_runtime_py/convert.py
=> simplify code using updated definition API

rosidl_generator_py/package.xml
=> Use semantic exec_depend key for python3-numpy.

rosidl_runtime_py/test/rosidl_runtime_py/test_set_message.py
Missed during #49.
Example build failure https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1179/testReport/
=> Update tests that were missed during switch to use new interfaces

rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/test/test_interfaces.py, rosidl_runtime_py/package.xml, rosidl_runtime_py/rosidl_runtime_py/convert.py, rosidl_runtime_py/rosidl_runtime_py/import_message.py, rosidl_runtime_py/rosidl_runtime_py/set_message.py, rosidl_runtime_py/test/rosidl_runtime_py/test_set_message.py
Replaces #30 now that #24 has merged
Required by ros2/ros2cli#207
Blocked by #34
=> store types as tuple of abstract types

rosidl_runtime_py/rosidl_runtime_py/convert.py
Related to ros2/ros2cli#154.
This makes the output of e.g. `ros2 topic echo ...` much easier to read:
* before: `wstring_value: "Hell\xF6 W\xF6rld!"`
* after: `wstring_value: Hellö Wörld!`
=> allow unicode chars in yaml output

rosidl_generator_py/package.xml
Fixes missing dependency.
http://build.ros2.org/view/Dbin_uB64/job/Dbin_uB64__rosidl_generator_py__ubuntu_bionic_amd64__binary/14/
=> add missing numpy test dependency

rosidl_generator_py/resource/_msg_support.c.em
This patch rolls back the changes from #26 and encodes / decodes (non W-)strings as UTF-8.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7091)](http://ci.ros2.org/job/ci_linux/7091/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3317)](http://ci.ros2.org/job/ci_linux-aarch64/3317/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5813)](http://ci.ros2.org/job/ci_osx/5813/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6913)](http://ci.ros2.org/job/ci_windows/6913/)
=> encode/decode strings with UTF-8

rosidl_generator_py/CMakeLists.txt
Fixes ros2/build_cop#209.
Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7076)](https://ci.ros2.org/job/ci_windows/7076/)
After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7077)](https://ci.ros2.org/job/ci_windows/7077/)
=> fix PYTHONPATH for test

rosidl_runtime_py/rosidl_runtime_py/set_message.py
If the type of the field is array.array, then a simple
x = array.array(mylist)
doesn't work; the typecode *must* be specified.  Special-case
arrays here so that we do:
x = array.array(typecode, list)
This should fix https://github.com/ros2/ros2cli/issues/270
=> Fix the setting of array variables.

rosidl_runtime_py/rosidl_runtime_py/set_message.py
Fixes #61 which is a consequence direct consequence of #59.
For array fields there is no need to try/except the construction. If it fails the exception should be raised as is.
This makes both examples work:
* `ros2 topic pub -r 5 /joy sensor_msgs/Joy "{header:{stamp:{sec: 0, nanosec: 0}, frame_id: 'frame'}, axes:[0.0], buttons:[0]}"`
* `ros2 topic pub -r 5 /foo std_msgs/Int32MultiArray '{layout: {dim: [{label: 'foo', size: 5, stride: 4}], data_offset: 12}, data: [1, 5.0]}'`
=> fix logic around populating arrays

rosidl_generator_py/resource/_msg.py.em
Before this patch, publishing a message with "ros2 topic pub"
would print something like:
publishing #5: my_msgs.msg.my_msg(axes=array('f', [0.0]))
While that is OK, it is kind of ugly.  This patch hides the
typecode and the "array" so that the output looks like:
publishing #5: my_msgs.msg.my_msg(axes=[0.0])
Which is also how it looked in Crystal.
Note that this is currently targeting the `fix-array-publish` branch; we'll need to retarget once that one is merged.  Also note that this is kind of an RFC; while it is quite ugly, it is a cosmetic issue, and touching the generated python code may be too risky for Dashing at this point.  I'll run CI presently, but opinions welcome.
=> Make the message __repr__ for python look nicer.

rosidl_generator_py/resource/_msg.py.em
It turns out that while all AbstractSequences are *defined*
to be arrays, we allow users to assign other sequences (like
lists) to those fields.  Make sure that the field starts with
'array(' before trying to strip it off.
This should fix https://github.com/ros2/build_cop/issues/212
=> Ensure the contents of the field are an array.

rosidl_runtime_py/rosidl_runtime_py/convert.py
Connects to https://github.com/ros2/ros2cli/issues/136
Signed-off-by: vinnamkim <vinnam.kim@gmail.com>
=> Add no_arr and no_str parameters

rosidl_runtime_py/rosidl_runtime_py/set_message.py, rosidl_runtime_py/test/rosidl_runtime_py/test_set_message.py
Fix #67
Signed-off-by: artivis <jeremie.deray@canonical.com>
=> handle set_message_fields given some non-basic type

rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_support.c.em
IDL and some programming languages like C require a struct to have at least one member. Python though doesn't have that restriction and can define a class without any slots.
Therefore this patch removes the member `structure_needs_at_least_one_member` only used to "pad" empty structures from the Python data type. As a consequence printing the message won't show the member as well as the user won't see a getter and setter for the member anymore.
In the conversion from Python to C the member variable present in C is just set to `0` in order to not be uninitialized. In the other direction the value in the C struct is just ignored and not transferred to the Python object.
Fixes ros2/ros2cli#297. Requires ros2/rosidl#389.
=> remove the padding member from structs which should be empty

rosidl_generator_py/resource/_msg_support.c.em
This avoids cpplint errors, for instance: https://ci.ros2.org/job/ci_linux/7594/testReport/test_msgs/cpplint_rosidl_generated_py/build_include__4____home_jenkins_agent_workspace_ci_linux_ws_build_test_msgs_rosidl_generator_py_test_msgs_srv__arrays_s_c_1462_/
Connects to https://github.com/ros2/rosidl/pull/387
=> Avoid multiple includes for nested array functions

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
Also set _FOUND to trick `ament_target_dependencies()` call for test
interfaces
blocks ament/ament_cmake#180
=> Remove non-package from ament_target_dependencies()

rosidl_runtime_py/rosidl_runtime_py/import_message.py, rosidl_runtime_py/rosidl_runtime_py/set_message.py, rosidl_runtime_py/test/rosidl_runtime_py/test_import_message.py
Fixes #70 
Instead of changing the type specification, which would either require changing the function name (breaking API) or have the name and the behavior mismatch (current state), this modifies the function to operate on `NamespacedType` instead.
This will change behavior for consumers of the function.
If this is not desired, the less disruptive alternative is to change the function specification without changing the function name or the behavior.
Added a simple test to cover the uses of the function used in this package.
=> Make import_message_from_namespaced_type operate on NamespacedType

rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
Update rosidl_generator_py to test for numpy headers exist on the python
include paths, and query numpy for its include path if the headers are
not found.
Resolves #66
Signed-off-by: Rich Mattes <richmattes@gmail.com>
=> Find numpy headers in non-debian paths

rosidl_runtime_py/rosidl_runtime_py/utilities.py, rosidl_runtime_py/test/rosidl_runtime_py/test_utilities.py
To avoid repeated code in some `ros2cli` packages.
See https://github.com/ros2/ros2cli/pull/301#discussion_r310283612.
=> Add utility functions to get interface from identifier

rosidl_runtime_py/rosidl_runtime_py/convert.py, rosidl_runtime_py/test/rosidl_runtime_py/test_convert.py
Also fix style by breaking after open parenthesis.
Addresses https://github.com/ros2/rosidl_python/pull/38#discussion_r306588426
=> Require keyword arguments be passed by name

rosidl_generator_py/test/test_interfaces.py
For legacy interfaces (ie. .msg, .srv, and .action), the 'char' is mapped to a 'uint8' type.
Resolves https://github.com/ros2/rosidl_python/issues/90
=> Enable tests for 'char' type fields

rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_support.c.em
Backport of #73. Depends on ros2/rosidl#424.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8728)](http://ci.ros2.org/job/ci_linux/8728/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4559)](http://ci.ros2.org/job/ci_linux-aarch64/4559/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7130)](http://ci.ros2.org/job/ci_osx/7130/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8643)](http://ci.ros2.org/job/ci_windows/8643/)
=> [dashing backport] remove pad field from py

rosidl_generator_py/resource/_msg_support.c.em
Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.
=> code style only: wrap after open parenthesis if not in one line

rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
This is a temporary fix related to issue #95. Until a language-specific name mangling is implemented to avoid keywords as described in ros2/design#172, a warning would be nice.
I can add stderr prints for services and actions also if this pull request seems like a good idea.
Example build output from colcon:
```
Starting >>> dredgebot_msgs
Starting >>> rosidl_generator_py
Finished <<< rosidl_generator_py [7.05s]                                                               
[Processing: dredgebot_msgs]                             
--- stderr: dredgebot_msgs                                  
Member name "from" in the message "LatLonLineSegment" is a reserved keyword in Python and is not supported at the moment. Please use a different name.
---
Finished <<< dredgebot_msgs [39.4s]
Summary: 2 …
```
=> Add warnings for reserved Python keywords in interface members

rosidl_generator_py/resource/_msg.py.em
Moving 'noqa: A003' for fields named like a builtin from the property to the method line.
Before:
* Linux Bionic: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9688)](https://ci.ros2.org/job/ci_linux/9688/)
* Linux Focal: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9689)](https://ci.ros2.org/job/ci_linux/9689/)
* macOS: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7905)](https://ci.ros2.org/job/ci_osx/7905/)
* Windows: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9593)](https://ci.ros2.org/job/ci_windows/9593/)
After:
* Linux Bionic: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9691)](https://ci.ros2.org/job/ci_linux/9691/)
* Linux Focal: [![Build …
=> move 'noqa: A003' for fields named like a builtin from property to method line

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake, rosidl_generator_py/package.xml
This PR is related to the changes introduced in this PR https://github.com/ros2/rosidl/pull/442. The full process can be followed here https://github.com/ros2/rosidl/issues/443
@wjwwood @dirk-thomas 
Signed-off-by: ahcorde <ahcorde@gmail.com>
=> added rosidl_runtime c and cpp depencencies

rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake, rosidl_generator_py/cmake/rosidl_generator_py_get_typesupports.cmake, rosidl_generator_py/package.xml
Needed for ros2/rmw_dds_common#12
=> remove dependency on rmw_implementation

rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
Fixes #106.
Before #102 the available RMW packages where enumerated and `rmw_connext_cpp` returned `not-found` if Connext wasn't available: https://github.com/ros2/rmw_connext/blob/ae1bc361b1ee77be826b37bc3d0b2a0d6caa34ec/rmw_connext_cpp/rmw_connext_cpp-extras.cmake#L21
After #102 RMW impl. aren't considered anymore but only the type support packages.
This patch checks for the actual existence of the typesupport specific target which is about to be used instead of any secondary state (package existence, index registration, extensions, etc.).
=> skip inoperable typesupport implementations

rosidl_generator_py/package.xml
Since we are generating interfaces for testing.
This is aiming to fix build failures on build.ros2.org, for example: http://build.ros2.org/job/Fbin_uF64__rosidl_generator_py__ubuntu_focal_amd64__binary/7
=> Add test dependency on rosidl_typesupport_c_packages

rosidl_generator_py/cmake/register_py.cmake, rosidl_generator_py/package.xml
Similar to https://github.com/ros2/rosidl/pull/485.
Required by https://github.com/ament/ament_cmake/pull/256.
=> Force extension points to be registered in order

rosidl_generator_py/package.xml, rosidl_generator_py/rosidl_generator_py/import_type_support_impl.py
New in Python 3.8, we should call os.add_dll_directory for directories
containing the DLLs we intend to import as well as their recursive
dependencies.
Connects to https://github.com/ros2/ci/pull/432
=> Explicitly add DLL directories for Windows before importing

rosidl_generator_py/package.xml
We're building test interfaces that depend on rpyutils. This should fix the Debian packaging job:
http://build.ros2.org/view/Fbin_uF64/job/Fbin_uF64__rosidl_generator_py__ubuntu_focal_amd64__binary/20/
Only testing up to rosidl_generator_py on Linux: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10829)](https://ci.ros2.org/job/ci_linux/10829/)
I don't expect the result to vary on the other platforms.
=> Add test_depend on rpyutils

rosidl_generator_py/resource/_msg_support.c.em
Fixes #104.
Windows debug builds only testing `test_communication`:
* Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11285)](https://ci.ros2.org/job/ci_windows/11285/)
* After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11329)](https://ci.ros2.org/job/ci_windows/11329/)
=> fix too early decref of WString when converting from Python to C

rosidl_generator_py/bin/rosidl_generator_py, rosidl_generator_py/package.xml, rosidl_generator_py/rosidl_generator_py/cli.py, rosidl_generator_py/rosidl_generator_py/generate_py_impl.py, rosidl_generator_py/setup.cfg
Built on top of https://github.com/ros2/rosidl/pull/567. Connected to https://github.com/ros2/rosidl/pull/565.
=> Expose Python code generation via rosidl generate CLI

rosidl_generator_py/package.xml
This PR removes a dependency from `rosidl_typesupport_connext_c`, since it will become no longer needed once `rmw_connext_cpp` is replaced by `rmw_connextdds`.
See [rticommunity/rmw_connextdds #9](https://github.com/rticommunity/rmw_connextdds/issues/9) for a list of related PRs, and an overview of all the changes required to replace [ros2/rmw_connext](https://github.com/ros2/rmw_connext) (`rmw_connext_cpp`) with [rticommunity/rmw_connextdds](https://github.com/rticommunity/rmw_connextdds) in the ROS2 source tree.
=> Remove dependency from rosidl_typesupport_connext_c

rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
This makes Python interfaces discoverable through `pkg_resources` and `importlib.metadata`. 
Full CI to be safe:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14692)](http://ci.ros2.org/job/ci_linux/14692/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9444)](http://ci.ros2.org/job/ci_linux-aarch64/9444/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12357)](http://ci.ros2.org/job/ci_osx/12357/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14835)](http://ci.ros2.org/job/ci_windows/14835/)
=> Install generated Python interfaces in a Python package

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/test/test_cli_extension.py
Precisely what the title says. Should've added this back in #123.
CI up to `rosidl_generator_py`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14723)](http://ci.ros2.org/job/ci_linux/14723/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9475)](http://ci.ros2.org/job/ci_linux-aarch64/9475/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12390)](http://ci.ros2.org/job/ci_osx/12390/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14869)](http://ci.ros2.org/job/ci_windows/14869/)
=> Add smoke test for CLI extension

rosidl_generator_py/resource/_msg_support.c.em
This is rather naive approach to improve perfomance of copying large amount of data from python to C.
I didn't remove old code, but instead I've added a check if data can be accessed using buffer protocol, and if the answer is yes then a sequence is copied in single step, if the answer is no, then fallback to previous method is used.
It seems to work for ROS2 version of carla_ros_bridge where we discovered this issues. It seems to be the same issue as described in https://github.com/ros2/rclpy/issues/763
=> Added optimization for copying arrays of simple types from python to C using buffer protocol

rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/test/test_interfaces.py
This pull request fixes the issue described below:
Floating-point types of different precision (`float32`/`float64` in ROS, `float`/`double` in rclcpp and DDS), are not handled properly in rclpy (and corresponding rosidl_python intefaces), as the type checks rely solely on Python's built-in float type.
For example, when publishing a double-sized floating point value (e.g., `3.5e+100`) as `float32` type, the data goes through various type checks at different places:
1. `if type(3.5e+100) is float` in `rosidl_runtime_py/set_message.py`,
2. `assert(isinstance(3.5e+100, float))` in the msg setter code automatically generated by rosidl,
and these checks don't reject this value as `3.5e+100` is of `float` type in Python, even though it is too big for a 32-bit float.
Then, when converting this …
=> add missing float/double bounds check

rosidl_generator_py/CMakeLists.txt
This should fix a test failure on Windows Debug where the test fails to import `numpy` extension modules.
https://ci.ros2.org/job/nightly_win_deb/2027/testReport/junit/(root)/projectroot/test_cli_extension/
=> Use python_d for test_cli_extension in Debug mode

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/rosidl_generator_py/cli.py, rosidl_generator_py/test/test_cli_extension.py
This patch allows the list of available typesupports to be narrowed down prior to generating Python C extensions through the `rosidl` CLI. Depends on ros2/rosidl#597. Built on top of #132.
CI up `rosidl_cli`, `rosidl_typesupport_c`, `rosidl_typesupport_cpp`, and `rosidl_generator_py`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14724)](http://ci.ros2.org/job/ci_linux/14724/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9476)](http://ci.ros2.org/job/ci_linux-aarch64/9476/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12391)](http://ci.ros2.org/job/ci_osx/12391/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14870)](http://ci.ros2.org/j …
=> Support available typesupport specification in CLI extension

rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
Part of ros2/rosidl#606 which deprecates `rosidl_target_interfaces()` in favor of `rosidl_get_typesupport_target()`
=> Use rosidl_get_typesupport_target()

rosidl_generator_py/resource/_msg_support.c.em
Backport https://github.com/ros2/rosidl_python/pull/129 to foxy
Related to #135
=> Added optimization for copying arrays of simple types from python to C using buffer protocol (backport #129)

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/msg/Property.msg, rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/test/test_property.py
The `@property`(s) of the constant(UPPER_CASE) and default({NAME}__DEFAULT) in the `Metaclass_Property` do not need to be updated.
to fix https://github.com/ros2/rosidl_python/issues/150
Signed-off-by: Chen Lihui <lihui.chen@sony.com>
=> fix for msg file containing a property field that is not at the end

rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
Requires ament/ament_cmake#371
rosidl_generator_py was assuming all interface packages being depended
upon call their interface generation target name `"${PROJECT_NAME}"`, but
that's an incorrect assumption. The target name is a required argument
to `rosidl_generate_interfaces()`. This fixes it by exporting the python
library target using an existing CMake macro for that purpose called
`rosidl_export_typesupport_targets()` and `ament_export_targets()`.
I works by adding a variable
`"${PROJECT_NAME}_TARGETS__rosidl_generator_py"` which is set when the
interface package is `find_package()`d. That variable contains the
targets generated by `rosidl_generator_py` so that downstream interface
packages can depend on it.
Since targets are being exported, a bug where build time include paths were …
=> Fix rosidl_generator_py assuming incorect library names

rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
We ran into an issue on a machine which had both Python 3.5 and Python 3.8 installed, and our software selected two different versions in various places. It seems that `PythonInterp` selected the 3.5 version even though the 3.8 was also there, seeming to prefer 3.5.x "exactly" instead of just "the newest" available.
Find the two versions is a different problem (two or more ways to find python in our CMake logic) that should be handled in a different set of pull requests, but the way the problem presented itself was that our Python code failed during the build of other packages due to the use of "format strings", which were introduced in Python 3.6. So this pull request (and a related one in `python_cmake_module`: https://github.com/ros2/python_cmake_module/pull/10) just do the bare …
=> require Python 3.6 as we use format strings in various places

rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
The sorting order for the module names changes after the call to `convert_camel_case_to_lower_case_underscore`. 
So copied the converted names to another variable and sorting those final names before writing to the file.
See #171 for details.
=> Fixing generated import order

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/package.xml, rosidl_generator_py/resource/_action.py.em, rosidl_generator_py/resource/_action_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_idl_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em, rosidl_generator_py/resource/_msg_support.c.em, rosidl_generator_py/resource/_srv.py.em, rosidl_generator_py/resource/_srv_pkg_typesupport_entry_point.c.em, rosidl_generator_py/rosidl_generator_py/generate_py_impl.py, rosidl_generator_py/test/test_interfaces.py
This pull request resolves the issue #162 by explicitly adding NaN values to the floating point bounds check.
Signed-off-by: Oystein Sture <os@skarvtech.com>
Fixes #169
Fixes #162
=> Allow NaN values to pass floating point bounds check.

rosidl_generator_py/test/test_interfaces.py
* The error is related to an unexpected keyword argument 'equal_nan' (Failing test [in rosidl PR](https://github.com/ros2/rosidl_python/pull/167/files#diff-f4b8ecb2aff8d495234eaf98c514cc3c04a8575d96aa46f29c5a137d894ff7c3R508)).
* We noticed this is a feature from numpy >= 1.19.0 (See https://github.com/numpy/numpy/pull/16128).
* Also, Windows Debug job has pinned numpy version to 1.18.4 [here](https://github.com/ros2/ci/blob/dabb6fd0f8357f727b7e73fbb41d07748bee6ad7/ros2_batch_job/__main__.py#L567).
Reference build: [Nightly Windows Debug](https://ci.ros2.org/view/nightly/job/nightly_win_deb/2458/testReport/junit/rosidl_generator_py.test/test_interfaces/test_arrays/)
Log output:
```
>       assert numpy.array_equal(arr_of_float32_with_nan, msg.float32_values, equal_nan=True) …
```
=> :man_farmer: Fix NaN values bound numpy windows version

rosidl_generator_py/resource/_msg.py.em
NumPy was being imported in the template code (not the template output) for no obvious reason. This was causing problems when cross-compiling, where NumPy may be only available for the target platform.
=> Remove stray numpy import

rosidl_generator_py/resource/_idl_support.c.em, rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/resource/_msg_support.c.em, rosidl_generator_py/resource/_srv.py.em, rosidl_generator_py/resource/_srv_pkg_typesupport_entry_point.c.em, rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
This PR is part of a prototype implementation for https://github.com/ros-infrastructure/rep/pull/360 https://github.com/ros2/ros2/issues/1285. 
Changes:
- Add <service_event>_Event message generation for services and actions
=> Service introspection

rosidl_generator_py/resource/_idl.py.em, rosidl_generator_py/resource/_msg.py.em, rosidl_generator_py/test/test_interfaces.py
This PR is related to the issue described in [this discussion](https://discourse.ros.org/t/high-cpu-load-for-simple-python-nodes/28324). After doing some benchmarks on simple publishers and subscribers on rclpy using different types of messages (Ex: Strings, Ints, Arrays, Custom messages with nested structures) and analyzing their behavior using flamegraphs, we noticed that a lot of the busy time of the nodes was being used during the creation of the messages object. Taking that into account, a possible area of improvement for this issue is by hiding all the assertions made on the fields of the messages under a user controlled flag.
In summary, this PR hides all the assertions made at the time of construction of messages in rclpy. In order to give the user control whether to do the …
=> Hides the assertions that checks the data types of the message fields.

rosidl_generator_py/package.xml
- Closes https://github.com/ros2/rosidl_python/issues/198
- Add a missing package in `package.xml`.
- Even if that the pkg in question is only required conditionally https://github.com/ros2/rosidl_python/issues/198#issuecomment-1636500998, it makes more sense to me in the upstream (here) to install it than making it a job for downstream pkgs.
- That said, I have little idea if the implementation I'm suggesting is the best/reasonable. Open for advises.
=> Fix: Missing dependency that causes cmake error in downstream (resolves https://github.com/ros2/rosidl_python/issues/198)

rosidl_generator_py/test/test_interfaces.py
This will fix a flake8 warning in newer versions.
=> Add in a missing space.

rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
There seems that some regression might have happened after #195. When removing those 2 lines, we avoid to install the .so files in lib *and* python path.
=> Revert install of .so files into python path

rosidl_generator_py/package.xml
Unlike the c/cpp packages, both generator and runtime facilities are provided by the same package for Python.
Corresponds to: https://github.com/ros2/rosidl_core/blob/84fa73d3974fe31fbe397e41e4449a31c2fb6ce4/rosidl_core_runtime/package.xml#L20
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20943)](http://ci.ros2.org/job/ci_linux/20943/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15234)](http://ci.ros2.org/job/ci_linux-aarch64/15234/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21617)](http://ci.ros2.org/job/ci_windows/21617/)
=> Add rosidl_generator_py to the rosidl_runtime_packages group

rosidl_generator_py/CMakeLists.txt, rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake, rosidl_generator_py/package.xml
This must be merged before https://github.com/ros2/ros2/pull/1524 ; see that pull request for more information about this change.
=> Remove python_cmake_module and set hints

rosidl_generator_py/resource/_msg_support.c.em
In an issue it was pointed out that we are decref'ing before we actually use some of the data, which means that in theory the garbage collector could reclaim the data before we used it.  So the original point of this change was to fix that issue.
However, while looking at it I realized we could slightly improve performance here by avoiding a copy of the class and module into a combined string.  Instead, we can compare them separately, which should reduce the copies.
This is a partial solution to https://github.com/ros2/rosidl_python/issues/217 ; the other reported bug in there will require a much more extensive rework.
=> Revamp how we check for the correct class.
